### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by roymacdonald** [roymacdonald/ofxLineaDeTiempo#1]
# TO DO
- [x] Implement scroll sliders for ofxMUI trying to rescue as much as possible from ofxTimeline2 and ofxPanels
- [x] scrollbar zoomers
- [x] Make functional mockup of the UI
- [x] make functional data holder that translates the ofParameter to add a time dimension.
	
- [x] Parameter sliders in header
- [x] implement time transport (time Controller).
	- [x]  code only
	- [x]  gui (just a simple panel with buttons and time code view)
	- [ ]  time translations (timecode, frame based, bpm and musically based.)

- [x] backend controller.
	holds data and syncs with gui. In charge of updating the ofParameter’s values.

- [x] Optimize:
	- [ ] rendering. Implement a single renderer class in charge of doing all. Use VboMeshes and an general Fbo which gets redrawn only when needed. Most of the time all items remain static, besides the playhead and time display
	- [x] gui updating. seems to be redundant. 
		- [ ]  Still more optimizatiion and cleaning seems posible

- [x] TImeRuler
	- [x] labels still needs a bit of improvement

- [ ] Trackheader
	- [x] Parameter Sliders
	- [ ] buttons
		- mute
		- solo
		- rec

- [ ] Implemented data types
	- [x] int8_t
	- [x] uint8_t
	- [x] int16_t
	- [x] uint16_t
	- [x] int32_t
	- [x] uint32_t
	- [x] int64_t
	- [x] uint64_t
	- [x] size_t
	- [x] float
	- [x] double
	- [x] glm::vec2
	- [x] glm::vec3
	- [x] glm::vec4
	- [ ] glm::quat (it is possible to tween between these using spherical lerp, although seems to be a glm experimental feature)
	- [ ] glm::mat4 (it is also possible to tween between these using glm::mix, although it is not implemented in ofxGui, so some more work needs to be done)
	- [x] bool
	- [x] void (because of how templating works you can not hold a void value so the whole timed data structures dont work. Yet, a simple list of the time where it gets triggered should work. Partially implemented in Keyframed)
	- [x] ofColor
	- [x] ofShortColor
	- [x] ofFloatColor
	- [ ] ofRectangle (it is partially supported in ofxGui.)
		- [ ] Make PR to the OF core with fix for full support in ofxGui

- [ ] Selector (selectors are mutually exclusive);
	- [x] Keyframes selector 	
	- [ ] Regions selector 
	- [ ] Select using keys

- [ ] Track
	- [ ] make selectable
	- [ ] Highlight when selected

- [ ] Region
	- [ ] make selectable
	- [ ] Highlight when selected
	- [x] activate/deactivate keyframes when inside/outside of it (when changing the region in and out)
	- [x] move keyframes when moving region (almost everything needed is there, just notify the controller about the dragging) 

- [x] TracksPanel
	- [x] Add GrabHandles to  for moving and resizing when autoFill is disabled.

- [x] TimeControl
	- [x] implement `trigger()` functon. ( Starts again from zero whenever called)

- [ ] Keyframes
	- [ ] non linear easing (use ofxEasing? or something simpler, use handles? bezier handles?)
- [ ] copy and paste. 
- [ ] undo/redo
- [x] mouse scroll usage 
	- [x] vert and horz move 
	- [ ] zoom in/out using modifier key. Center zooming on mouse position

- [ ] Keyboard shortcuts manager. 

- [ ] Examples:
	- [x] Basic
	- [x] AllParameterTypes (needs cleanup)
	- [x] second window
	- [x] not adjusting to window
	- [ ]  independent timelines
	- [ ]  One timeline triggers another one

## Timeline GUI Structure
- Main container: inherits from track group . 
	- Timeruler and playhead. (it is also in charge of making the time to pixel and pixel to time conversions)
	- Track Headers
		- Track Header (has pointer to the track, and moves and scales following the track)
	- Tracks panel : 
		- Other trackGroups
			- Track
		- Track (stores pointer to header. keeps the ofParameter)
			- Regions
				- Background( render video or waveform or nothing)
				- KeyFrames
					- KeyFrame
						- time
						- value (float, which then translates to the ofParameter)

**Comment by awilkie1** [comment]
Might want to consider Strings, noticed that its an ofParameter but not accessible in here.

**Comment by roymacdonald** [comment]
Thanks @awilkie1 
I will add strings. I left em out as I thought it did not make sense to have strings in the timeline but then I realized that these can be used as a "named bang";
best

**Comment by awilkie1** [comment]
Yes, would be super useful! I'm making an OSC/UDP tool, being able to make bangs containing string which can be inputted via the GUI would be super slick
